# This file was generated by WriteXDCFile from collected XDCAnnotations.

create_generated_clock -name buildtop_reference_clock -source [get_pins -of [get_clocks host_clock]] [get_pins top/sim/target/FireSim_/clockBridge_clocks_0_buffer/O] -divide_by 1
set_multicycle_path 1 -setup -from [get_clocks buildtop_reference_clock] -to [get_clocks buildtop_reference_clock]
set_multicycle_path 0 -hold  -from [get_clocks buildtop_reference_clock] -to [get_clocks buildtop_reference_clock]
